<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Anggota;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class AnggotaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'program_studi_id' => 1,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Andi Saputra',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jayapura',
                'tanggal_lahir' => '1999-05-14',
                'agama' => 'Islam',
                'alamat_tinggal' => 'Jl. Merdeka No. 10, Jayapura',
                'no_hp' => '081234567890',
                'email' => 'andi@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '190001',
                'ktp' => null,
                'status' => 'Baru',
                'alumni' => NULL,
                'keterangan' => 'Aktif dalam organisasi',
            ],
            [
                'id' => 2,
                'program_studi_id' => 2,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Siti Nurhaliza',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Manokwari',
                'tanggal_lahir' => '2000-01-22',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Jl. Pendidikan No. 5, Manokwari',
                'no_hp' => '082345678901',
                'email' => 'siti@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '200002',
                'ktp' => null,
                'status' => 'Pindah Masuk',
                'alumni' => NULL,
                'keterangan' => null,
            ],
            [
                'id' => 3,
                'program_studi_id' => 3,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Joko Santoso',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sorong',
                'tanggal_lahir' => '1998-08-08',
                'agama' => 'Katolik',
                'alamat_tinggal' => 'Jl. Bahagia No. 8, Sorong',
                'no_hp' => '083456789012',
                'email' => 'joko@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '180003',
                'ktp' => null,
                'status' => 'Pindah Keluar',
                'alumni' => 2000,
                'keterangan' => 'Sudah lulus',
            ],
            [
                'id' => 4,
                'program_studi_id' => 2,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Maria Goreti',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Timika',
                'tanggal_lahir' => '2001-12-01',
                'agama' => 'Katolik',
                'alamat_tinggal' => 'Jl. Kemerdekaan No. 11, Timika',
                'no_hp' => '084567890123',
                'email' => 'maria@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '210004',
                'ktp' => null,
                'status' => 'Draft',
                'alumni' => NULL,
                'keterangan' => 'Peserta baru',
            ],
            [
                'id' => 5,
                'program_studi_id' => 1,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Rian Wibowo',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Nabire',
                'tanggal_lahir' => '2002-03-30',
                'agama' => 'Islam',
                'alamat_tinggal' => 'Jl. Damai No. 20, Nabire',
                'no_hp' => '085678901234',
                'email' => 'rian@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '220005',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => null,
            ],
            [
                'id' => 6,
                'program_studi_id' => 3,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Yohana Pahabol',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Wamena',
                'tanggal_lahir' => '2001-09-10',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Jl. Yos Sudarso No. 17, Wamena',
                'no_hp' => '081122334455',
                'email' => 'yohana@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '210006',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Koordinator wilayah',
            ],
            [
                'id' => 7,
                'program_studi_id' => 1,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Samuel Tabuni',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Dekai',
                'tanggal_lahir' => '1997-02-20',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Kampung Dekai Indah',
                'no_hp' => '081998877665',
                'email' => 'samuel@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '170007',
                'ktp' => null,
                'alumni' => 2020,
                'keterangan' => 'Sudah bekerja di Jayapura',
            ],
            [
                'id' => 8,
                'program_studi_id' => 2,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Eva Wambrauw',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Biak',
                'tanggal_lahir' => '1996-06-06',
                'agama' => 'Katolik',
                'alamat_tinggal' => 'Jl. Pantai Bosnik, Biak',
                'no_hp' => '082334455667',
                'email' => 'eva@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '160008',
                'ktp' => null,
                'alumni' => 2021,
                'keterangan' => 'Mengikuti pelatihan wirausaha',
            ],
            [
                'id' => 9,
                'program_studi_id' => 3,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Daniel Toding',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Merauke',
                'tanggal_lahir' => '2000-10-12',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Jl. Trans Papua, Merauke',
                'no_hp' => '085512348765',
                'email' => 'daniel@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '200009',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Bendahara organisasi',
            ],
            [
                'id' => 10,
                'program_studi_id' => 2,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Ruth Waromi',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Serui',
                'tanggal_lahir' => '1998-11-01',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Jl. Raya Serui, Serui',
                'no_hp' => '081234908765',
                'email' => 'ruth@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '180010',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Sekretaris organisasi',
            ],
            [
                'id' => 11,
                'program_studi_id' => 1,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Fredi Kobak',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Enarotali',
                'tanggal_lahir' => '1999-04-19',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Jl. YPPGI Enarotali',
                'no_hp' => '083366677788',
                'email' => 'fredi@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '190011',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Peserta pelatihan Laravel',
            ],
            [
                'id' => 12,
                'program_studi_id' => 2,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Vina Tabuni',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Ilaga',
                'tanggal_lahir' => '2003-07-23',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Kampung Ilaga Tengah',
                'no_hp' => '089912345671',
                'email' => 'vina@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '230012',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Baru mendaftar',
            ],
            [
                'id' => 13,
                'program_studi_id' => 3,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Nando Way',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Fakfak',
                'tanggal_lahir' => '1995-02-01',
                'agama' => 'Islam',
                'alamat_tinggal' => 'Jl. Irian Jaya, Fakfak',
                'no_hp' => '081345678943',
                'email' => 'nando@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '150013',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Lulus tahun 2020',
            ],
            [
                'id' => 14,
                'program_studi_id' => 1,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Lukas Yeremias',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Karubaga',
                'tanggal_lahir' => '2002-11-11',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Jl. Karubaga Sentral',
                'no_hp' => '085600123456',
                'email' => 'lukas@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '220014',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Peserta aktif',
            ],
            [
                'id' => 15,
                'program_studi_id' => 2,
                'tanggal_pendaftaran' => Carbon::now(),
                'nama_lengkap' => 'Helena Kambu',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yahukimo',
                'tanggal_lahir' => '1999-03-03',
                'agama' => 'Kristen',
                'alamat_tinggal' => 'Jl. Pasar Yahukimo',
                'no_hp' => '081776655443',
                'email' => 'helena@example.com',
                'foto' => null,
                'kpm' => null,
                'nim' => '190015',
                'ktp' => null,
                'alumni' => NULL,
                'keterangan' => 'Dalam masa orientasi',
            ],
        ];
        

        foreach ($data as $item) {
            \App\Models\Anggota::create($item);
        }
    }
}
